env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - eslint:recommended
  - react-app

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - react-hooks

rules:
  import/extensions: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/jsx-props-no-spreading: 1
  react-hooks/exhaustive-deps: 0
  no-trailing-spaces: 1
  object-curly-newline: 1
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/functional-parameters: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
