env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react

rules:
  import/extensions: 0
  react/prop-types: 0
